# Site settings
title: learn 1 Do 1
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The best way to learn is to teach. 
  Understanding is a work in progress
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username: learn1do1 

# Build settings
markdown: kramdown

paginate: 4

author: Occam

gems: [jekyll-paginate]
